# Version of the config.yml
version: "v2.0.0"

# Name of the challenge
name: 'Scanner or Not?'

#Difficulty: 10 - 500
difficulty: 30

#Enable inputbox to submit flag: true | false
enable_flag_input: true

# If the solution is a fix string (static flag) you can add it here
flag: 'ssh'

# Skills related to the challenge: ['SQL injection','Web','Linux']
skills: ['Metasploit','Offensive', 'Scanning','Linux']

# Recommended readings
recommendations:
    https://www.offensive-security.com: 'Some Metasploit possibilities'
    https://www.offensive-security.com/metasploit-unleashed/vulnerability-scanning/: 'Scanning'
    https://metasploit.help.rapid7.com/docs/discovery-scan: 'Discovery scanning via Metasploit'

# The emails of the Intellectual Property (IP) owners. Note that it is also possible that the owner is the same as the content creator.
owners: ['409773@mail.muni.cz']

# CRP Config
crp_config:
    solvable:
        # Required Linux capabilities (See http://man7.org/linux/man-pages/man7/capabilities.7.html for the full list).
        # For example ["SETGID","SETUID"]
        # capabilities: [] # Not needed if empty
        ports: ['666/tcp']
