version: 'v2.0.0'
# Name of the challenge
name: 'Magic Tool'
# Challenge difficulty: 10 - 500
difficulty: 10
# Enable inputbox to submit flag: true | false
enable_flag_input: true
# If the solution is a fix string (static flag) you can add it here
flag: '2012'
# Skills related to the challenge: ['Metasploit','Find','Linux']
skills: ['Metasploit','Find','Linux', 'Offensive']
# Recommended readings
recommendations:
    https://www.offensive-security.com/metasploit-unleashed/: 'Some Metasploit possibilities'
# The emails of the Intellectual Property (IP) owners. Note that it is also possible that the owner is the same as the content creator.
owners: ['409773@mail.muni.cz']
